// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkofrfxscokivtkkkyle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrb2ZyZnhzY29raXZ0a2treWxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjM4MDgsImV4cCI6MjA2MTU5OTgwOH0.Qm591ZeyDS5Hkj3cnJzpa9RE20l-fkVD9Mqb8NRbjSk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);